In [108]:
import tensorflow as tf

In [109]:
ta = tf.zeros((2,2))

In [110]:
print(ta.eval())

[[0. 0.]
 [0. 0.]]


In [111]:
session = tf.InteractiveSession() #명령행에서 텐서플로 세션 사용

In [112]:
print(ta.eval())

[[0. 0.]
 [0. 0.]]


In [113]:
session.close()

In [114]:
W1=tf.zeros((3,3))

In [115]:
W2=tf.Variable(tf.zeros((2,2)),name='weights')

In [116]:
session=tf.InteractiveSession()

In [117]:
session.run(tf.global_variables_initializer()) #초기화 함수를 run() 함수의 인자로 넣어 실행

In [118]:
print(W1.eval())

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [119]:
print(W2.eval())

[[0. 0.]
 [0. 0.]]


In [120]:
input1 = tf.placeholder(tf.float32,3) #tf.float32형 값을 3개 가지는 플레이스홀더

In [121]:
input2 = tf.placeholder(tf.float32) #tf.float32형 값을 가지는 플레이스홀더

In [122]:
output = tf.multiply(input1, input2)

In [123]:
session = tf.InteractiveSession()

In [124]:
print(session.run([output], feed_dict={input1:[1.,2.,3.], input2:[3.]}))

[array([3., 6., 9.], dtype=float32)]


In [125]:
session = tf.InteractiveSession()

In [126]:
a = tf.constant(2)

In [127]:
b = tf.constant(3)

In [128]:
x = tf.add(a,b)

In [129]:
writer = tf.summary.FileWriter('./graphs', session.graph)

In [130]:
session.run(x)

5

In [131]:
writer.close()

In [132]:
session.close()

In [133]:
session = tf.InteractiveSession()

In [134]:
a = tf.constant(2, name='a')

In [135]:
b = tf.constant(3, name='b')

In [136]:
x = tf.add(a,b)

In [137]:
writer = tf.summary.FileWriter('./graphs', session.graph)

In [138]:
session.run(x)

5

In [139]:
writer.close()

In [140]:
session.close()